### ISSUE TITLE
The specified log stream already exists

### ISSUE THREAD

**Issue by szahnfender** [jenkinsci/aws-cloudwatch-logs-publisher-plugin#21]
If the log group already exists, it throws an exception:

```
ERROR: Build step failed with exception
com.amazonaws.services.logs.model.ResourceAlreadyExistsException: The specified log stream already exists (Service: AWSLogs; Status Code: 400; Error Code: ResourceAlreadyExistsException; Request ID: e92391f0-6232-11e9-ae1d-570f3e51afe9)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1695)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1350)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520)
	at com.amazonaws.services.logs.AWSLogsClient.doInvoke(AWSLogsClient.java:2597)
	at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:2564)
	at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:2553)
	at com.amazonaws.services.logs.AWSLogsClient.executeCreateLogStream(AWSLogsClient.java:722)
	at com.amazonaws.services.logs.AWSLogsClient.createLogStream(AWSLogsClient.java:694)
	at jenkins.plugins.awslogspublisher.AWSLogsHelper.pushToAWSLogs(AWSLogsHelper.java:108)
Caused: java.lang.RuntimeException: [AWS Logs] Unable to create log stream 'sfcc-order-export-build' in log group '/jenkins/jobs' (com.amazonaws.services.logs.model.ResourceAlreadyExistsException: The specified log stream already exists (Service: AWSLogs; Status Code: 400; Error Code: ResourceAlreadyExistsException; Request ID: e92391f0-6232-11e9-ae1d-570f3e51afe9))
	at jenkins.plugins.awslogspublisher.AWSLogsHelper.pushToAWSLogs(AWSLogsHelper.java:113)
	at jenkins.plugins.awslogspublisher.AWSLogsHelper.publish(AWSLogsHelper.java:51)
	at jenkins.plugins.awslogspublisher.AWSLogsPublisher.showStreamInfo(AWSLogsPublisher.java:60)
	at jenkins.plugins.awslogspublisher.AWSLogsPublisher.perform(AWSLogsPublisher.java:53)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'AWS CloudWatch Logs Publisher' marked build as failure
Finished: FAILURE
```

**Comment by rnhurt** [comment]
Yes, I'm getting the same thing.  On the first run of a job, it creates the log stream and everything is fine.  However, on subsequent jobs I get the error that the "The specified log stream already exists", even though this job was the one that created it.  

Are we supposed to use a unique name for each job stream?  If so, is there a way to do this?  Perhaps using Jenkins build environment variables or something?

**Comment by rnhurt** [comment]
Good news!  I can confirm that [Jenkins Environment Variables](https://wiki.jenkins.io/display/JENKINS/Building+a+software+project) work in the "Log stream name" configuration!  

I used `$BUILD_TAG` as my "Log stream name" and it creates a new stream for each build.  BEAUTIFUL! 

NOTE: this should probably be in the README or PlugIn documentation.  :)
